language: rust

rust:
  - stable
  - beta
  - nightly

before_script:
  - |
    pip install 'travis-cargo' --user &&
    export PATH=$HOME/.local.bin:$PATH
script:
  - |
    travis-cargo build &&
    travis-cargo test

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=channel_select

notifications:
  email:
    - pmunksgaard@gmail.com
    - laumann.thomas@gmail.com
